# Sample .travis.yml for R projects

language: r
cache: packages
#warnings_are_errors: true
#sudo: required

r:
#  - oldrel
  - release
  - devel


#r_github_packages:
#  - cran/survival
#  - jimhester/covr

#r_packages:
#  - covr

after_success:
  - Rscript -e 'covr::codecov(type=c("all"))'
  